cand = """
## POSSIBLE ROOT CAUSE COMPONENTS:

- aiops-k8s-01
- aiops-k8s-02
- aiops-k8s-03
- aiops-k8s-04
- aiops-k8s-05
- aiops-k8s-06
- aiops-k8s-07
- aiops-k8s-08"""

schema = f"""## DATASET STRUCTURE:

- You can access the data directory in our microservices system: `dataset/phaseone/`.

- This directory contains subdirectories organized by a date (e.g., `dataset/phaseone/2025-06-06/`). 

- Within each date-specific directory, you'll find these subdirectories: `metric-parquet`, `trace-parquet`, and `log-parquet` (e.g., `dataset/phaseone/2025-06-06/metric-parquet/`).

- The data in `trace-parquet` and `log-parquet` subdirectories is stored in parquet format (e.g., `dataset/phaseone/2025-06-06/log-parquet/log_filebeat-server_2025-06-06_00-00-00.parquet`).

- Within 'metric-parquet' directory, you will find these subdirectories: `apm`, `infra` and `other`.

- For `metric-parquet` subdirectory, the internal data folder structure is shown below:

```plaintext
dataset/phaseone/2025-06-06/metric-parquet/
├── apm/
│   ├── pod/
|   |   ├── pod_adservice-0_2025-06-06.parquet
│   |   └── ...
|   ├── service/
|   |   ├── service_adservice_2025-06-06.parquet
|   |   └── ...
│   └── pod_ns_hipstershop_2025-06-06.parquet
├── infra/
│   ├── infra_node/
|   |   └── infra_node_node_cpu_usage_rate_2025-06-06.parquet
|   ├── infra_pod/
|   |   └── infra_pod_pod_cpu_usage_2025-06-06.parquet
│   └── infra_tidb/
|       └── infra_tidb_block_cache_size_2025-06-06.parquet
└── other/
|   ├── infra_pd_abnormal_region_count_2025-06-06.parquet
    └── ...
```

## DATA SCHEMA

1.  **Metric Files** (in metric-parquet/):
    
    1. `apm/pod/*.parquet`:
        ```csv
        timestamp,pod_name,value
        1687035600,checkoutservice-0,0.15
        ```
        - pod级别的APM指标数据
        - value代表具体指标值(如CPU使用率、内存使用量等)

    2. `apm/service/*.parquet`:
        ```csv
        timestamp,service_name,value
        1687035600,checkoutservice,0.25
        ```
        - service级别的APM指标数据
        - value表示服务级别的性能指标

    3. `infra/infra_node/*.parquet`:
        ```csv
        timestamp,node,value
        1687035600,aiops-k8s-01,45.2
        ```
        - 节点级别的基础设施指标
        - value表示节点资源使用情况

2.  **Trace Files** (in trace-parquet/):
    ```csv
    timestamp,trace_id,span_id,parent_span_id,service,operation,duration,status
    1687035602123,abc123,span1,parent1,frontend,HTTP GET,150,OK
    ```
    - timestamp: 毫秒级时间戳
    - service: 服务名称
    - operation: 操作名称
    - duration: 调用耗时(ms)
    - status: 调用状态

3.  **Log Files** (in log-parquet/):
    ```csv
    timestamp,service,level,content
    1687035600,checkoutservice,ERROR,"Connection refused to database"
    ```
    - timestamp: 秒级时间戳
    - service: 产生日志的服务名称
    - level: 日志级别(INFO/WARN/ERROR等)
    - content: 日志具体内容

## 补充说明:

1. 所有时间戳相关说明:
   - metric数据: 秒级时间戳
   - trace数据: 毫秒级时间戳
   - log数据: 秒级时间戳
   - 时区统一使用UTC+8

2. 服务命名规则:
   - checkoutservice
   - orderservice
   - paymentservice 
   - 等标准服务名称

3. 数据采样周期:
   - metrics: 15秒/次
   - traces: 实时采集
   - logs: 实时采集


{cand}

## CLARIFICATION OF TELEMETRY DATA:

1. This dataset is generated by builted microservice system.

2. File Name Time Format:
   - Using CST timezone (UTC+8)
   - Example: log_filebeat-server_2025-06-06_00-00-00.parquet
   - Represents 00:00:00 on June 6, 2025 in Beijing time

3. In different data files, the timestamp formats vary:

   - Metric Data:
     Format: 2025-06-05T16:00:00Z (UTC timezone)
     Example: 2025-06-05T16:00:00Z equals to 2025-06-06 00:00:00 in Beijing time

   - Log Data: 
     Format: 2025-06-05T16:00:29.045Z (UTC timezone)
     Example: 2025-06-05T16:00:29.045Z equals to 2025-06-06 00:00:29.045 in Beijing time

   - Trace Data:
     Format: Unix timestamp in milliseconds
     Example: 1749139200377 (startTimeMillis field)

4. Timezone Conversion Notes:
   - File names use Beijing time (CST/UTC+8)
   - Data content uses UTC time
   - All timestamps are in UTC
   - For analysis: UTC+8 = Beijing time
"""